---
services: docker

env:
  # Defaults.
  - distro: centos7
    test_idempotence: false

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/sylus/e5d6eb8852d649ae78477b2daf86e707/raw
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

notifications:
  slack:
    secure: sji3A1BsMRGEI51mnfb66RHmuLcsaOdVeJT604FByzin5GS3MC17CpEFiwE81mznD4jzZg/gR7FQ2LwlafjqmaKXhtGd9yNUfTAa2h8MXXzx7rWny2hN428fbw/ELlg4WT6A7WU7bYmoBZVEF18+8ubyU2n+WSKN2hPlBYs3S04O9dZrqK0icS51lnNchG+pXEzOXmlft7896095tkxcHFL4PvxokntHHdHZz9vEVqktlQZN7TwmiHu6/y1E8sF0N+xOvd27NSCI32AVSHMMQqL9W/BUuof4uVLSy3bcKIcnhkT/ce9xdUiTdJ/e1zsanQwqmywhHu4Emm52FcJ+exoyje6T3PXWF+20RzDG1BrNezUaUg2+ho92WJGycPLdrXJjthbwuNZWexC1E8I0gNNCPTWB2AmomDDLvs3Cp56+WaezQHU8Jwp2Td4UfRIZBJ2em9QiBKcd6IuvlWfqxjtHoQJNn6uOt8URiPerSnv5I9Ilx22qtXa6vqh3NadWgT14Lm7fD2aVRZQbcrgo3LuCd87A6DjuhX8O5RadFbYwM2QXltKO/MQD/SOs5DO40C/SfUDHKr2tL6mm4Q/S/APzr+XYXdxAkjQRL7yBVRHOy8D843+iZWPbCOZ7Z2JMzlkpzOtYc3dcFX2MsDd7TNTKikFc/9m3mX+RFqP2Pmg=
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
